import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 시작: 데이터베이스 시드...');

  // 기존 약물 데이터 삭제 (개발 환경에서만)
  await prisma.medicine.deleteMany();
  console.log('✅ 기존 약물 데이터 삭제 완료');

  // 샘플 약물 데이터
  const medicines = [
    // 해열진통제
    {
      name: '타이레놀정 500mg',
      genericName: '아세트아미노펜',
      company: '한국얀센',
      className: '해열진통제',
      effect: '두통, 치통, 발열, 근육통 등의 통증 완화',
      usage: '성인 1회 1-2정, 1일 3-4회 복용',
      sideEffects: '드물게 오심, 구토, 식욕부진, 피부발진 등',
      precautions: '음주 시 복용 금지. 장기 복용 시 간 손상 위험.',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    {
      name: '아스피린',
      genericName: '아세틸살리실산',
      company: '바이엘코리아',
      className: '해열진통제',
      effect: '두통, 치통, 발열, 근육통 완화 및 혈전 예방',
      usage: '성인 1회 1정, 1일 3회 복용',
      sideEffects: '위장장애, 출혈 시간 연장, 알레르기 반응',
      precautions: '위장장애 예방을 위해 식후 복용. 출혈 위험 주의.',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: true,
      mealTiming: 'AFTER_MEAL',
    },
    {
      name: '게보린정',
      genericName: '아세트아미노펜, 에텐자미드, 카페인',
      company: '삼진제약',
      className: '해열진통제',
      effect: '두통, 치통, 발열, 근육통 등의 통증 완화',
      usage: '성인 1회 1정, 1일 3회 복용',
      sideEffects: '드물게 오심, 불면, 초조, 떨림 등',
      precautions: '카페인 함유로 저녁 복용 시 수면 방해 가능',
      sleepInducing: 'NONE',
      alertnessEffect: 'MEDIUM',
      stomachIrritation: false,
      mealTiming: 'AFTER_MEAL',
    },
    {
      name: '판콜에이내복액',
      genericName: '아세트아미노펜, 슈도에페드린, 클로르페니라민',
      company: '동화약품',
      className: '종합감기약',
      effect: '감기로 인한 제반 증상 완화 (콧물, 코막힘, 발열, 두통)',
      usage: '성인 1회 1포, 1일 3회 복용',
      sideEffects: '졸음, 구갈, 두통, 오심 등',
      precautions: '졸음이 올 수 있으므로 운전 및 기계 조작 시 주의',
      sleepInducing: 'HIGH',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'AFTER_MEAL',
    },
    {
      name: '지르텍정 10mg',
      genericName: '세티리진',
      company: '유씨비코리아',
      className: '항히스타민제',
      effect: '알레르기성 비염, 두드러기 등 알레르기 증상 완화',
      usage: '성인 1회 1정, 1일 1회 복용',
      sideEffects: '졸음, 피로감, 구갈, 두통 등',
      precautions: '졸음을 유발할 수 있으므로 취침 전 복용 권장',
      sleepInducing: 'MEDIUM',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    {
      name: '암씨롱정',
      genericName: '디히드록시알루미늄나트륨',
      company: '중외제약',
      className: '제산제',
      effect: '위산과다, 속쓰림, 위통 완화',
      usage: '성인 1회 1-2정, 1일 3-4회 복용',
      sideEffects: '드물게 변비, 설사 등',
      precautions: '식후 1-2시간 또는 속쓰림 시 복용',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'AFTER_MEAL',
    },
    {
      name: '부루펜정 400mg',
      genericName: '이부프로펜',
      company: '삼일제약',
      className: '소염진통제',
      effect: '염증, 통증, 발열 완화',
      usage: '성인 1회 1정, 1일 3회 복용',
      sideEffects: '위장장애, 오심, 속쓰림, 발진 등',
      precautions: '위장장애 예방을 위해 식후 복용 권장',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: true,
      mealTiming: 'AFTER_MEAL',
    },
    {
      name: '박카스정',
      genericName: '티아민질산염, 리보플라빈, 니코틴산아미드 등',
      company: '동아제약',
      className: '비타민제',
      effect: '육체피로, 병중병후 체력저하 시 영양보급',
      usage: '성인 1회 1정, 1일 2-3회 복용',
      sideEffects: '드물게 설사, 구역, 발진 등',
      precautions: '과량 복용 시 불면 가능',
      sleepInducing: 'NONE',
      alertnessEffect: 'LOW',
      stomachIrritation: false,
      mealTiming: 'AFTER_MEAL',
    },
    {
      name: '베아제정',
      genericName: '판크레아틴',
      company: '대웅제약',
      className: '소화효소제',
      effect: '소화불량, 식욕부진 개선',
      usage: '성인 1회 2-3정, 1일 3회 식후 복용',
      sideEffects: '드물게 설사, 복부불쾌감 등',
      precautions: '식후 즉시 복용',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'AFTER_MEAL',
    },
    {
      name: '훼스탈골드정',
      genericName: '판크레아틴, 헤미셀룰라아제, 우르소데옥시콜산',
      company: '한국아벤티스',
      className: '소화효소제',
      effect: '소화불량, 과식, 식욕부진 개선',
      usage: '성인 1회 1정, 1일 3회 식후 복용',
      sideEffects: '드물게 설사, 변비, 구역 등',
      precautions: '식후 즉시 복용',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'AFTER_MEAL',
    },
    {
      name: '알레르기정',
      genericName: '클로르페니라민',
      company: '국제약품',
      className: '항히스타민제',
      effect: '알레르기성 비염, 피부 가려움, 두드러기 완화',
      usage: '성인 1회 1정, 1일 3-4회 복용',
      sideEffects: '졸음, 구갈, 두통, 현기증 등',
      precautions: '강한 졸음을 유발할 수 있으므로 운전, 기계 조작 시 주의',
      sleepInducing: 'HIGH',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    // 고혈압약
    {
      name: '노바스크정 5mg',
      genericName: '암로디핀',
      company: '한국화이자제약',
      className: '고혈압치료제',
      effect: '고혈압, 협심증 치료',
      usage: '성인 1일 1회 복용',
      sideEffects: '부종, 두통, 어지러움, 피로감',
      precautions: '아침 또는 저녁 일정한 시간에 복용',
      sleepInducing: 'LOW',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    {
      name: '디오반정 80mg',
      genericName: '발사르탄',
      company: '노바티스',
      className: '고혈압치료제',
      effect: '고혈압 치료',
      usage: '성인 1일 1회 복용',
      sideEffects: '어지러움, 피로감, 두통',
      precautions: '일정한 시간에 복용. 임신 중 금기.',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    // 당뇨약
    {
      name: '메트포민정 500mg',
      genericName: '메트포르민',
      company: '유한양행',
      className: '당뇨병치료제',
      effect: '제2형 당뇨병 치료',
      usage: '성인 1일 2-3회 식후 복용',
      sideEffects: '오심, 설사, 복통, 식욕부진',
      precautions: '식후 복용. 신기능 주의.',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: true,
      mealTiming: 'AFTER_MEAL',
    },
    {
      name: '아마릴정 2mg',
      genericName: '글리메피리드',
      company: '사노피',
      className: '당뇨병치료제',
      effect: '제2형 당뇨병 치료',
      usage: '성인 1일 1회 아침 식사 직전 또는 식사 중 복용',
      sideEffects: '저혈당, 오심, 두통',
      precautions: '저혈당 주의. 식사와 함께 복용.',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'WITH_MEAL',
    },
    // 콜레스테롤약
    {
      name: '리피토정 10mg',
      genericName: '아토르바스타틴',
      company: '한국화이자',
      className: '고지혈증치료제',
      effect: '고콜레스테롤혈증, 고지혈증 치료',
      usage: '성인 1일 1회 복용',
      sideEffects: '근육통, 소화불량, 두통',
      precautions: '저녁 복용 권장. 근육통 발생 시 의사 상담.',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    {
      name: '크레스토정 10mg',
      genericName: '로수바스타틴',
      company: '한국아스트라제네카',
      className: '고지혈증치료제',
      effect: '고콜레스테롤혈증 치료',
      usage: '성인 1일 1회 복용',
      sideEffects: '근육통, 두통, 어지러움',
      precautions: '저녁 복용 권장. 자몽주스와 함께 복용 금지.',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    // 위장약
    {
      name: '넥시움정 40mg',
      genericName: '에소메프라졸',
      company: '한국아스트라제네카',
      className: '위산분비억제제',
      effect: '위염, 역류성식도염, 소화성궤양 치료',
      usage: '성인 1일 1회 식전 복용',
      sideEffects: '두통, 설사, 오심',
      precautions: '식전 복용. 장기 복용 시 의사 상담.',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'BEFORE_MEAL',
    },
    {
      name: '가스모틴정',
      genericName: '모사프리드',
      company: '대웅제약',
      className: '위장관운동촉진제',
      effect: '소화불량, 속쓰림, 구역 개선',
      usage: '성인 1회 1정, 1일 3회 식전 복용',
      sideEffects: '설사, 복통, 두통',
      precautions: '식전 복용. 임산부 주의.',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'BEFORE_MEAL',
    },
    // 항생제
    {
      name: '오구멘틴정',
      genericName: '아모시실린, 클라불란산',
      company: 'GSK',
      className: '항생제',
      effect: '세균 감염증 치료',
      usage: '성인 1회 1정, 1일 3회 식후 복용',
      sideEffects: '설사, 오심, 발진',
      precautions: '처방 기간 동안 규칙적으로 복용. 임의 중단 금지.',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: true,
      mealTiming: 'AFTER_MEAL',
    },
    // 천식약
    {
      name: '싱귤레어정 10mg',
      genericName: '몬테루카스트',
      company: 'MSD',
      className: '천식치료제',
      effect: '천식, 알레르기성 비염 예방 및 치료',
      usage: '성인 1일 1회 취침 전 복용',
      sideEffects: '두통, 복통, 설사',
      precautions: '취침 전 복용 권장',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    // 갑상선약
    {
      name: '신지로이드정 100mcg',
      genericName: '레보티록신',
      company: '한국애보트',
      className: '갑상선호르몬제',
      effect: '갑상선기능저하증 치료',
      usage: '성인 1일 1회 공복에 복용',
      sideEffects: '불면, 심계항진, 떨림',
      precautions: '아침 공복에 복용. 식사 30분 전.',
      sleepInducing: 'NONE',
      alertnessEffect: 'HIGH',
      stomachIrritation: false,
      mealTiming: 'BEFORE_MEAL',
    },
    // 수면제
    {
      name: '스틸녹스정 10mg',
      genericName: '졸피뎀',
      company: '사노피',
      className: '수면제',
      effect: '불면증 치료',
      usage: '성인 취침 직전 1정 복용',
      sideEffects: '졸음, 어지러움, 두통',
      precautions: '취침 직전 복용. 운전 금지. 의존성 주의.',
      sleepInducing: 'HIGH',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    // 항우울제
    {
      name: '렉사프로정 10mg',
      genericName: '에스시탈로프람',
      company: '한국룬드벡',
      className: '항우울제',
      effect: '우울증, 불안장애 치료',
      usage: '성인 1일 1회 복용',
      sideEffects: '오심, 불면, 졸음, 성기능 장애',
      precautions: '일정한 시간에 복용. 임의 중단 금지.',
      sleepInducing: 'LOW',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    // 더 많은 해열진통제
    {
      name: '애드빌',
      genericName: '이부프로펜',
      company: '한국화이자',
      className: '해열진통제',
      effect: '두통, 치통, 근육통, 생리통, 발열',
      usage: '성인 1회 1-2정, 1일 3회',
      sideEffects: '위장장애, 속쓰림, 오심',
      precautions: '식후 복용 권장. 위궤양 병력 주의.',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: true,
      mealTiming: 'AFTER_MEAL',
    },
    {
      name: '이지엔6',
      genericName: '이부프로펜, 아세트아미노펜',
      company: 'CJ헬스케어',
      className: '해열진통제',
      effect: '두통, 치통, 생리통, 관절통',
      usage: '성인 1회 1정, 1일 3회',
      sideEffects: '위장장애, 오심, 구토',
      precautions: '식후 복용. 음주 시 간 손상 주의.',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: true,
      mealTiming: 'AFTER_MEAL',
    },
    {
      name: '펜잘큐정',
      genericName: '덱시부프로펜',
      company: '삼진제약',
      className: '소염진통제',
      effect: '관절염, 근육통, 치통',
      usage: '성인 1회 1정, 1일 2-3회',
      sideEffects: '위장장애, 소화불량',
      precautions: '식후 복용. 궤양 병력자 주의.',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: true,
      mealTiming: 'AFTER_MEAL',
    },
    // 감기약
    {
      name: '판피린티정',
      genericName: '아세트아미노펜, 클로르페니라민',
      company: '동아제약',
      className: '감기약',
      effect: '감기로 인한 발열, 두통, 콧물',
      usage: '성인 1회 2정, 1일 3회',
      sideEffects: '졸음, 구갈, 오심',
      precautions: '졸음 유발. 운전 주의.',
      sleepInducing: 'HIGH',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'AFTER_MEAL',
    },
    {
      name: '콘택600',
      genericName: '슈도에페드린, 클로르페니라민',
      company: 'GSK',
      className: '감기약',
      effect: '감기로 인한 코막힘, 콧물',
      usage: '성인 1일 2회',
      sideEffects: '졸음, 불면, 두근거림',
      precautions: '졸음과 각성 효과 동시 가능',
      sleepInducing: 'MEDIUM',
      alertnessEffect: 'MEDIUM',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    {
      name: '테라플루',
      genericName: '아세트아미노펜, 페닐레프린',
      company: 'GSK',
      className: '감기약',
      effect: '감기 증상 완화',
      usage: '성인 1회 1포, 1일 3-4회',
      sideEffects: '졸음, 오심',
      precautions: '따뜻한 물에 타서 복용',
      sleepInducing: 'MEDIUM',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    // 항히스타민제
    {
      name: '알레그라정',
      genericName: '펙소페나딘',
      company: '사노피',
      className: '항히스타민제',
      effect: '알레르기성 비염, 두드러기',
      usage: '성인 1일 2회',
      sideEffects: '두통, 오심',
      precautions: '비진정성 항히스타민제',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    {
      name: '클라리틴정',
      genericName: '로라타딘',
      company: '바이엘',
      className: '항히스타민제',
      effect: '알레르기 증상 완화',
      usage: '성인 1일 1회',
      sideEffects: '두통, 졸음',
      precautions: '졸음 적음',
      sleepInducing: 'LOW',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    {
      name: '아타락스정',
      genericName: '히드록시진',
      company: 'UCB',
      className: '항히스타민제',
      effect: '두드러기, 가려움증',
      usage: '성인 1일 3-4회',
      sideEffects: '강한 졸음',
      precautions: '취침 전 복용 권장',
      sleepInducing: 'HIGH',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    // 고혈압약 추가
    {
      name: '코자정',
      genericName: '로사르탄',
      company: 'MSD',
      className: '고혈압치료제',
      effect: '고혈압 치료',
      usage: '성인 1일 1회',
      sideEffects: '어지러움, 피로',
      precautions: '일정한 시간에 복용',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    {
      name: '트윈스타정',
      genericName: '텔미사르탄, 암로디핀',
      company: '베링거인겔하임',
      className: '고혈압치료제',
      effect: '고혈압 치료',
      usage: '성인 1일 1회',
      sideEffects: '부종, 어지러움',
      precautions: '복합제. 아침 복용 권장.',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    {
      name: '아프로벨정',
      genericName: '이르베사르탄',
      company: '사노피',
      className: '고혈압치료제',
      effect: '고혈압 치료',
      usage: '성인 1일 1회',
      sideEffects: '어지러움, 두통',
      precautions: '임신 중 금기',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    {
      name: '올메텍정',
      genericName: '올메사르탄',
      company: '대웅제약',
      className: '고혈압치료제',
      effect: '고혈압 치료',
      usage: '성인 1일 1회',
      sideEffects: '어지러움',
      precautions: '식사와 관계없이 복용',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    // 당뇨약 추가
    {
      name: '다이아벡스정',
      genericName: '메트포르민',
      company: '중외제약',
      className: '당뇨병치료제',
      effect: '제2형 당뇨병',
      usage: '성인 1일 2-3회 식후',
      sideEffects: '설사, 복통, 오심',
      precautions: '식후 복용. 신기능 확인.',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: true,
      mealTiming: 'AFTER_MEAL',
    },
    {
      name: '자누비아정',
      genericName: '시타글립틴',
      company: 'MSD',
      className: '당뇨병치료제',
      effect: '제2형 당뇨병',
      usage: '성인 1일 1회',
      sideEffects: '두통, 저혈당',
      precautions: '식사와 관계없이 복용',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    {
      name: '트라젠타정',
      genericName: '리나글립틴',
      company: '베링거인겔하임',
      className: '당뇨병치료제',
      effect: '제2형 당뇨병',
      usage: '성인 1일 1회',
      sideEffects: '두통, 비인두염',
      precautions: '식사와 관계없이',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    // 위장약 추가
    {
      name: '란스톤정',
      genericName: '란소프라졸',
      company: '유한양행',
      className: '위산분비억제제',
      effect: '위염, 역류성식도염',
      usage: '성인 1일 1회 아침 식전',
      sideEffects: '설사, 두통',
      precautions: '아침 식전 복용',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'BEFORE_MEAL',
    },
    {
      name: '오메프라졸',
      genericName: '오메프라졸',
      company: '동아에스티',
      className: '위산분비억제제',
      effect: '위궤양, 역류성식도염',
      usage: '성인 1일 1-2회 식전',
      sideEffects: '두통, 복통',
      precautions: '식전 30분 복용',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'BEFORE_MEAL',
    },
    {
      name: '모티리톤정',
      genericName: '모티리톤',
      company: '동아에스티',
      className: '위장관운동조절제',
      effect: '기능성 소화불량',
      usage: '성인 1일 3회 식전',
      sideEffects: '설사, 복통',
      precautions: '식전 복용',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'BEFORE_MEAL',
    },
    {
      name: '탈시온정',
      genericName: '레바미피드',
      company: '대웅제약',
      className: '위점막보호제',
      effect: '위염, 위궤양',
      usage: '성인 1일 3회 식후',
      sideEffects: '변비, 설사',
      precautions: '식후 복용',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'AFTER_MEAL',
    },
    // 항생제 추가
    {
      name: '세파클러캡슐',
      genericName: '세파클러',
      company: '유한양행',
      className: '항생제',
      effect: '세균 감염증',
      usage: '성인 1일 3회 식후',
      sideEffects: '설사, 발진',
      precautions: '처방 기간 준수',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: true,
      mealTiming: 'AFTER_MEAL',
    },
    {
      name: '클라리스로마이신',
      genericName: '클라리스로마이신',
      company: '한미약품',
      className: '항생제',
      effect: '호흡기 감염',
      usage: '성인 1일 2회',
      sideEffects: '오심, 복통',
      precautions: '식후 복용 권장',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: true,
      mealTiming: 'AFTER_MEAL',
    },
    {
      name: '시프로플록사신',
      genericName: '시프로플록사신',
      company: '바이엘',
      className: '항생제',
      effect: '요로감염, 호흡기감염',
      usage: '성인 1일 2회',
      sideEffects: '오심, 설사',
      precautions: '충분한 수분 섭취',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: true,
      mealTiming: 'AFTER_MEAL',
    },
    // 진통제 추가
    {
      name: '트라마돌',
      genericName: '트라마돌',
      company: '유한양행',
      className: '마약성진통제',
      effect: '중등도 이상의 통증',
      usage: '성인 1일 3-4회',
      sideEffects: '졸음, 어지러움, 오심',
      precautions: '졸음 유발. 운전 금지.',
      sleepInducing: 'HIGH',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    {
      name: '셀레콕시브',
      genericName: '셀레콕시브',
      company: '한국화이자',
      className: '소염진통제',
      effect: '관절염, 통증',
      usage: '성인 1일 1-2회',
      sideEffects: '소화불량, 부종',
      precautions: '심혈관 위험 주의',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: true,
      mealTiming: 'AFTER_MEAL',
    },
    // 천식/호흡기약
    {
      name: '세레타이드',
      genericName: '플루티카손, 살메테롤',
      company: 'GSK',
      className: '천식치료제',
      effect: '천식, 만성폐쇄성폐질환',
      usage: '성인 1일 2회 흡입',
      sideEffects: '목쉼, 구강칸디다증',
      precautions: '흡입 후 입 헹구기',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    {
      name: '심비코트',
      genericName: '부데소니드, 포르모테롤',
      company: '아스트라제네카',
      className: '천식치료제',
      effect: '천식 예방 및 치료',
      usage: '성인 1일 2회 흡입',
      sideEffects: '목쉼, 두통',
      precautions: '흡입 후 양치',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    // 골다공증약
    {
      name: '포사맥스정',
      genericName: '알렌드로네이트',
      company: 'MSD',
      className: '골다공증치료제',
      effect: '골다공증 치료 및 예방',
      usage: '성인 주 1회 또는 1일 1회',
      sideEffects: '식도염, 복통',
      precautions: '아침 공복에 복용 후 30분간 눕지 않기',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: true,
      mealTiming: 'BEFORE_MEAL',
    },
    {
      name: '본비바정',
      genericName: '이반드로네이트',
      company: '로슈',
      className: '골다공증치료제',
      effect: '골다공증',
      usage: '성인 월 1회',
      sideEffects: '소화불량, 근육통',
      precautions: '아침 공복 복용',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: true,
      mealTiming: 'BEFORE_MEAL',
    },
    // 심장약
    {
      name: '콩코르정',
      genericName: '비소프롤롤',
      company: 'MSD',
      className: '베타차단제',
      effect: '고혈압, 협심증',
      usage: '성인 1일 1회 아침',
      sideEffects: '서맥, 피로, 어지러움',
      precautions: '갑작스런 중단 금지',
      sleepInducing: 'LOW',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    {
      name: '프라비딕스정',
      genericName: '프라수그렐',
      company: '다이이찌산쿄',
      className: '항혈소판제',
      effect: '혈전 예방',
      usage: '성인 1일 1회',
      sideEffects: '출혈',
      precautions: '출혈 위험 주의',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    {
      name: '플라빅스정',
      genericName: '클로피도그렐',
      company: '사노피',
      className: '항혈소판제',
      effect: '혈전 예방',
      usage: '성인 1일 1회',
      sideEffects: '출혈, 소화불량',
      precautions: '수술 전 중단 필요',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: true,
      mealTiming: 'ANYTIME',
    },
    // 항진균제
    {
      name: '라미실정',
      genericName: '테르비나핀',
      company: '노바티스',
      className: '항진균제',
      effect: '피부 진균 감염',
      usage: '성인 1일 1회',
      sideEffects: '소화불량, 발진',
      precautions: '간기능 검사 필요',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    // 항바이러스제
    {
      name: '팜시클로버정',
      genericName: '팜시클로버',
      company: '한미약품',
      className: '항바이러스제',
      effect: '대상포진, 헤르페스',
      usage: '성인 1일 3회',
      sideEffects: '두통, 오심',
      precautions: '충분한 수분 섭취',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    // 이뇨제
    {
      name: '라식스정',
      genericName: '푸로세미드',
      company: '사노피',
      className: '이뇨제',
      effect: '부종, 고혈압',
      usage: '성인 1일 1-2회 아침',
      sideEffects: '저칼륨혈증, 어지러움',
      precautions: '아침 복용. 취침 전 피함.',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    // 항경련제
    {
      name: '뉴론틴캡슐',
      genericName: '가바펜틴',
      company: '한국화이자',
      className: '항경련제',
      effect: '신경병증성 통증, 간질',
      usage: '성인 1일 3회',
      sideEffects: '졸음, 어지러움',
      precautions: '졸음 유발. 점진적 증량.',
      sleepInducing: 'MEDIUM',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    {
      name: '리리카캡슐',
      genericName: '프레가발린',
      company: '한국화이자',
      className: '항경련제',
      effect: '신경병증성 통증',
      usage: '성인 1일 2회',
      sideEffects: '졸음, 어지러움, 체중증가',
      precautions: '강한 졸음. 취침 전 복용 고려.',
      sleepInducing: 'HIGH',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    // 항응고제
    {
      name: '쿠마딘정',
      genericName: '와파린',
      company: '한국BMS',
      className: '항응고제',
      effect: '혈전 예방',
      usage: '성인 1일 1회',
      sideEffects: '출혈',
      precautions: '정기적 혈액검사 필요. 비타민K 섭취 주의.',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    {
      name: '자렐토정',
      genericName: '리바록사반',
      company: '바이엘',
      className: '항응고제',
      effect: '혈전 예방',
      usage: '성인 1일 1회',
      sideEffects: '출혈',
      precautions: '출혈 위험. 신기능 확인.',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    // 통풍약
    {
      name: '알로푸리놀정',
      genericName: '알로푸리놀',
      company: '유한양행',
      className: '통풍치료제',
      effect: '통풍, 고요산혈증',
      usage: '성인 1일 1-3회 식후',
      sideEffects: '발진, 소화불량',
      precautions: '충분한 수분 섭취',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: true,
      mealTiming: 'AFTER_MEAL',
    },
    {
      name: '페브릭정',
      genericName: '페북소스타트',
      company: '대웅제약',
      className: '통풍치료제',
      effect: '통풍',
      usage: '성인 1일 1회',
      sideEffects: '간기능 이상, 발진',
      precautions: '간기능 검사',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    // 비타민/영양제
    {
      name: '센트룸멀티비타민',
      genericName: '종합비타민',
      company: 'GSK',
      className: '비타민제',
      effect: '영양 보급',
      usage: '성인 1일 1회',
      sideEffects: '드물게 소화불량',
      precautions: '식후 복용 권장',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'AFTER_MEAL',
    },
    {
      name: '비타민D',
      genericName: '콜레칼시페롤',
      company: '일동제약',
      className: '비타민제',
      effect: '비타민D 보충',
      usage: '성인 1일 1회',
      sideEffects: '드물게 변비',
      precautions: '지용성 비타민. 과량 주의.',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'AFTER_MEAL',
    },
    {
      name: '오메가3',
      genericName: 'EPA, DHA',
      company: '종근당',
      className: '영양제',
      effect: '혈행 개선',
      usage: '성인 1일 1-2회',
      sideEffects: '드물게 소화불량',
      precautions: '식후 복용',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'AFTER_MEAL',
    },
    // 근이완제
    {
      name: '마이날정',
      genericName: '에페리손',
      company: '한미약품',
      className: '근이완제',
      effect: '근육 긴장, 경직',
      usage: '성인 1일 3회',
      sideEffects: '졸음, 어지러움',
      precautions: '졸음 유발 가능',
      sleepInducing: 'MEDIUM',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    // 기타 소화기계
    {
      name: '콜로폴캡슐',
      genericName: '트리메부틴',
      company: '한국아벤티스',
      className: '과민성대장증후군치료제',
      effect: '과민성대장증후군',
      usage: '성인 1일 3회 식전',
      sideEffects: '변비, 설사',
      precautions: '식전 복용',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'BEFORE_MEAL',
    },
    {
      name: '스멕타현탁액',
      genericName: '디오스멕타이트',
      company: '입센',
      className: '지사제',
      effect: '설사',
      usage: '성인 1일 3회',
      sideEffects: '변비',
      precautions: '다른 약과 2시간 간격',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    // 항불안제
    {
      name: '자낙스정',
      genericName: '알프라졸람',
      company: '한국화이자',
      className: '항불안제',
      effect: '불안장애, 공황장애',
      usage: '성인 1일 2-3회',
      sideEffects: '졸음, 어지러움',
      precautions: '의존성 주의. 서서히 감량.',
      sleepInducing: 'HIGH',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    {
      name: '아티반정',
      genericName: '로라제팜',
      company: '한국화이자',
      className: '항불안제',
      effect: '불안, 긴장',
      usage: '성인 1일 2-3회',
      sideEffects: '졸음, 근육 이완',
      precautions: '중독성. 단기 사용.',
      sleepInducing: 'HIGH',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    // 피부과약
    {
      name: '피나스테리드',
      genericName: '피나스테리드',
      company: 'MSD',
      className: '탈모치료제',
      effect: '남성형 탈모',
      usage: '성인 1일 1회',
      sideEffects: '성욕감퇴',
      precautions: '임산부 접촉 금지',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
    // 안과약 (경구)
    {
      name: '루테인',
      genericName: '루테인',
      company: '종근당',
      className: '눈영양제',
      effect: '눈 건강',
      usage: '성인 1일 1회',
      sideEffects: '드물게 소화불량',
      precautions: '식후 복용',
      sleepInducing: 'NONE',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'AFTER_MEAL',
    },
    // 기침약
    {
      name: '덱스트로메토르판',
      genericName: '덱스트로메토르판',
      company: '한미약품',
      className: '진해제',
      effect: '기침',
      usage: '성인 1일 3-4회',
      sideEffects: '졸음, 오심',
      precautions: '졸음 가능',
      sleepInducing: 'LOW',
      alertnessEffect: 'NONE',
      stomachIrritation: false,
      mealTiming: 'ANYTIME',
    },
  ];

  // 약물 데이터 삽입
  for (const medicine of medicines) {
    await prisma.medicine.create({
      data: medicine,
    });
  }

  console.log(`✅ ${medicines.length}개의 약물 데이터 추가 완료`);
  console.log('🎉 데이터베이스 시드 완료!');
}

main()
  .catch((e) => {
    console.error('❌ 시드 중 오류 발생:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
